[package]
name = "tari_comms_dht"
version = "0.0.5"
authors = ["The Tari Development Community"]
description = "Tari comms DHT module"
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_comms = { version = "^0.0", path = "../"}
tari_crypto = { version = "^0.0", path = "../../infrastructure/crypto"}
tari_utilities = { version = "^0.0", path = "../../infrastructure/tari_util"}
tari_shutdown = { version = "^0.0", path = "../../infrastructure/shutdown"}
tari_comms_middleware = { version = "^0.0", path = "../middleware"}

bitflags = "1.2.0"
bytes = "0.4.12"
chrono = "0.4.9"
derive-error = "0.0.4"
digest = "0.8.1"
futures= {version= "0.3.0-alpha.19", package="futures-preview"}
log = "0.4.8"
prost = "0.5.0"
rand = "0.5.5"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_repr = "0.1.5"
tokio = "0.2.0-alpha.6"
tokio-executor = "0.2.0-alpha.6"
tower-filter= {path="../middleware/tower-filter"}#version="=0.3.0-alpha.2", path="../"
tower= "0.3.0-alpha.2"
ttl_cache = "0.5.1"
prost-types = "0.5.0"

[dev-dependencies]
tari_test_utils = { version = "^0.0", path = "../../infrastructure/test_utils"}
tari_storage = { version = "^0.0", path = "../../infrastructure/storage"}

futures-test = { version = "0.3.0-alpha.19", package = "futures-test-preview" }
lmdb-zero = "0.4.4"
tempdir = "0.3.7"
env_logger = "0.7.0"

[build-dependencies]
tari_protobuf_build = { version = "^0.0", path="../../infrastructure/protobuf_build"}
