[package]
name = "tari_test_utils"
version = "0.0.2"
authors = ["The Tari Development Community"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-test = { version = "0.3.0-alpha.18", package = "futures-test-preview" }
futures= {version= "0.3.0-alpha.18", package="futures-preview"}
rand = "0.7.0"
tokio = "0.2.0-alpha.4"
tokio-executor = "0.2.0-alpha.4"
lazy_static = "1.3.0"
