[package]
name = "tari_key_manager"
authors = ["The Tari Development Community"]
description = "Tari cryptocurrency wallet key management"
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.0.5"
edition = "2018"

[dependencies]
tari_crypto = { path = "../../infrastructure/crypto", version = "^0.0" }
tari_utilities = { path = "../../infrastructure/tari_util", version = "^0.0" }
rand = "0.5.5"
digest = "0.8.0"
sha2 = "0.8.0"
derive-error = "0.0.4"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"

