[package]
name = "tari_transactions"
description = "Core Tari blockchain primitives"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.0.5"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_crypto = { path = "../../infrastructure/crypto", version = "^0.0" }
tari_utilities = { path = "../../infrastructure/tari_util", version = "^0.0", features = ["chrono_dt"]}

lazy_static = "1.3.0"
serde = { version = "1.0.97", features = ["derive"] }
digest = "0.8.0"
bitflags = "1.0.4"
newtype-ops = "0.1.4"
derive-error = "0.0.4"
prost = "0.5.0"
bytes = "0.4.12"
prost-types = "0.5.0"
bincode = "1.1.4"
serde_json = "1.0"
chrono = { version = "0.4.6"}

[build-dependencies]
tari_protobuf_build = { version = "^0.0", path="../../infrastructure/protobuf_build"}

[dev-dependencies]
rand = "0.5.5"
