[package]
name = "windows_service_installer"
version = "0.1.0"
authors = ["Strider"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows-service = "0.3.1"