[package]
name = "tari_service_framework"
version = "0.0.5"
authors = ["The Tari Development Community"]
description = "The Tari communication stack service framework"
repository = "https://github.com/tari-project/tari"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_shutdown = { version = "^0.0", path="../../infrastructure/shutdown" }

derive-error = "0.0.4"
futures = { version = "=0.3.0-alpha.19", package = "futures-preview", features=["async-await"]}
tower-service = { version="0.3.0-alpha.2" }
tokio = "0.2.0-alpha.6"

[dev-dependencies]
tari_test_utils = { version = "^0.0", path="../../infrastructure/test_utils" }
futures-test = { version = "0.3.0-alpha.19", package = "futures-test-preview" }
