[package]
name = "tari_p2p"
version = "0.0.5"
description = "Tari base layer-specific peer-to-peer communication features"
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
edition = "2018"

[dependencies]
tari_broadcast_channel = { version="^0.0",  path = "../../infrastructure/broadcast_channel" }
tari_comms = { version = "^0.0", path = "../../comms"}
tari_comms_dht = { version = "^0.0", path = "../../comms/dht"}
tari_comms_middleware = { version = "^0.0", path = "../../comms/middleware"}
tari_crypto = { version = "^0.0", path = "../../infrastructure/crypto"}
tari_pubsub = { version = "^0.0", path = "../../infrastructure/pubsub"}
tari_service_framework = { version = "^0.0", path = "../service_framework"}
tari_shutdown = { version = "^0.0", path="../../infrastructure/shutdown" }
tari_storage = {version = "^0.0", path = "../../infrastructure/storage"}
tari_utilities = { version = "^0.0", path = "../../infrastructure/tari_util"}

bytes = "0.4.12"
chrono = { version = "0.4.6", features = ["serde"]}
derive-error = "0.0.4"
futures = { version = "=0.3.0-alpha.19", package = "futures-preview"}
lmdb-zero = "0.4.4"
log = "0.4.6"
prost = "0.5.0"
rand = "0.6.5"
serde = "1.0.90"
serde_derive = "1.0.90"
tokio = "0.2.0-alpha.6"
tower = "0.3.0-alpha.2"
tower-service = { version="0.3.0-alpha.2" }

[dev-dependencies]
tari_test_utils = { version = "^0.0", path="../../infrastructure/test_utils" }

clap = "2.33.0"
crossbeam-channel = "0.3.8"
cursive = "0.12.0"
env_logger = "0.6.2"
futures-test = { version = "0.3.0-alpha.19", package = "futures-test-preview" }
futures-timer = "0.3.0"
lazy_static = "1.3.0"
stream-cancel = "0.4.4"
tempdir = "0.3.7"
get_if_addrs = "0.5.3"

[dev-dependencies.log4rs]
version ="0.8.3"
features = ["console_appender", "file_appender", "file", "yaml_format"]
default-features = false

[build-dependencies]
tari_protobuf_build = { version = "^0.0", path="../../infrastructure/protobuf_build"}
