[package]
name = "merklemountainrange"
description = "A general Merkle Mountain Range implementation and API"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.0.2"
edition = "2018"

[dependencies]
tari_utilities = { path = "../tari_util", version = "^0.0" }
derive-error = "0.0.4"
digest = "0.8.0"
tari_storage = { path = "../storage", version = "^0.0" }
serde = "1.0.91"
serde_derive = "1.0.91"
rmp-serde = "0.13.7"

[dev-dependencies]
blake2 = "0.8.0"
tari_infra_derive= {path = "../derive"}
log = "0.4.6"
simple_logger = "1.2.0"
rand = "0.6.5"