[package]
name = "tari_core"
description = "Core Tari protocol components"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.0.5"
edition = "2018"

[dependencies]
tari_transactions = { path = "../../base_layer/transactions", version = "^0.0" }
tari_comms = { version = "^0.0", path = "../../comms"}
tari_utilities = { path = "../../infrastructure/tari_util", version = "^0.0", features = ["chrono_dt"]}
tari_infra_derive = { path = "../../infrastructure/derive", version = "^0.0" }
tari_crypto = { path = "../../infrastructure/crypto", version = "^0.0" }
tari_storage = { path = "../../infrastructure/storage", version = "^0.0" }
tari_common = {path = "../../common", version= "^0.0"}
tari_mmr = { path = "../../base_layer/mmr", version = "^0.0" }
tari_service_framework = { version = "^0.0", path = "../service_framework"}
tari_p2p = {path = "../../base_layer/p2p", version = "^0.0"}
tari_comms_dht = { version = "^0.0", path = "../../comms/dht"}
tari_broadcast_channel = { version="^0.0",  path = "../../infrastructure/broadcast_channel" }
tari_pubsub = { version = "^0.0", path = "../../infrastructure/pubsub"}
tari_shutdown = { path = "../../infrastructure/shutdown", version = "^0.0"}

bitflags = "1.0.4"
chrono = { version = "0.4.6", features = ["serde"]}
digest = "0.8.0"
derive-error = "0.0.4"
rand = "0.5.5"
serde = { version = "1.0.97", features = ["derive"] }
rmp-serde = "0.13.7"
base64 = "0.10.1"
serde_json = "1.0"
lazy_static = "1.3.0"
newtype-ops = "0.1.4"
arrayref = "0.3.5"
bincode = "1.1.4"
log = "0.4"
blake2 = "^0.8.0"
bigint = "^4.4.1"
ttl_cache = "0.5.1"
croaring = "=0.3.9"
tokio = { version="^0.2.0-alpha.6" }
tokio-executor = { version ="^0.2.0-alpha.6", features = ["threadpool"] }
futures-preview = {version = "0.3.0-alpha.19", features = ["async-await"] }
lmdb-zero = "0.4.4"
tower-service = { version="0.3.0-alpha.2" }
crossbeam-channel = "0.3.8"
prost = "0.5.0"
bytes = "0.4.12"
prost-types = "0.5.0"

[dev-dependencies]
env_logger = "0.7.0"
tari_test_utils = { path = "../../infrastructure/test_utils", version = "^0.0" }
tempdir = "0.3.7"

[build-dependencies]
tari_protobuf_build = { version = "^0.0", path="../../infrastructure/protobuf_build"}
