[package]
name = "tari_comms"
description = "A peer-to-peer messaging system"
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.0.5"
edition = "2018"

[dependencies]
tari_crypto = { version="^0.0",  path = "../infrastructure/crypto" }
tari_storage = { version="^0.0", path = "../infrastructure/storage" }
tari_utilities = { version="^0.0",  path = "../infrastructure/tari_util" }
tari_shutdown = { version="^0.0",  path = "../infrastructure/shutdown" }

bitflags ="1.0.4"
bytes = "0.4.12"
chrono = { version = "0.4.6", features = ["serde"] }
clear_on_drop = "0.2.3"
derive-error = "0.0.4"
digest = "0.8.0"
futures =  { version = "=0.3.0-alpha.19", package = "futures-preview", features =[ "async-await"]}
lazy_static = "1.3.0"
lmdb-zero = "0.4.4"
log = { version = "0.4.0", features = ["std"] }
prost = "0.5.0"
rand = "0.5.5"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_repr = "0.1.5"
time = "0.1.42"
tokio = "0.2.0-alpha.6"
tokio-executor = { version ="^0.2.0-alpha.6", features = ["threadpool"] }
ttl_cache = "0.5.1"
zmq = "0.9.2"

[dev-dependencies]
tari_test_utils = {path="../infrastructure/test_utils"}

criterion = "0.2"
rand = "0.5.5"
env_logger = "0.7.0"
futures-test = { version = "0.3.0-alpha.19", package = "futures-test-preview" }
serde_json = "1.0.39"
tari_common = { path = "../common", version = "^0.0" }
tokio-mock-task = "0.1.1"

[[bench]]
name = "benches_main"
harness = false

[build-dependencies]
tari_protobuf_build = { version = "^0.0", path="../infrastructure/protobuf_build"}
